#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: wordCounter
#          uri: http://localhost:8080
#          predicates:
#           - path= /wordCounter/**

server:
  port:
    8082